# Generated by Django 5.1.2 on 2024-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_videoprogress_equipamento_time_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='plataforma_watched',
            field=models.IntegerField(default=0),
        ),
    ]
