# Generated by Django 5.1.2 on 2024-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_videoprogress_plataforma_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='plataforma_watched',
            field=models.BooleanField(default=False),
        ),
    ]
